### ISSUE TITLE
1.5.3 v145

### ISSUE THREAD

**Issue by BahaStriker** [huludini/pw-api#1]
Can you setup the protocol for this version or it uses the same as 1.5.1 v101 ?

**Comment by DrZed** [comment]
It's not functioning for me, says server offline even though I changed the config.php to fit GACD on port 29702
I changed the version to 101 in the config as well
And I have had the server running for 12 hours now and it still doesn't show (I also restarted the whole machine it's hosted on and started the server back up and still no dice)

**Comment by MateusCouto** [comment]
> Can you setup the protocol for this version or it uses the same as 1.5.1 v101 ?

https://github.com/MateusCouto/PWTools-Meridiano/tree/main/_web/api-rest/pw
